import { Poppins } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  display: "swap",
  weight: ["200", "300", "500"],
  subsets: ["latin"],
});

export const metadata = {
  title: "Basic Bukit Asam",
  description: "Generated by Basic Bukit Asam",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>{children}</body>
    </html>
  );
}
